### ISSUE TITLE
在底部上拉载入更多时，没有正在加载的指示图标

### ISSUE THREAD

**Issue by shengbinmeng** [shengbinmeng/UniBBS#23]
如题。当时用的第三方库，估计已经不靠谱了。

**Comment by fanyingming** [comment]
检测到底部后自动加载更多

**Comment by shengbinmeng** [comment]
我是说加载更多时应该显示一个转圈的图标，就像顶部下拉刷新那样。顶部下拉刷新用的是系统提供的refreshControl，底部上拉用了一个第三方的bottomRefreshControll，但是好像有问题……

**Comment by shengbinmeng** [comment]
改为了瀑布流的形式，自动加载更多了。参见提交：https://github.com/shengbinmeng/UniBBS/commit/d3ff38d1eb019a202d0fd12a0f67968ba48dc7eb
