### ISSUE TITLE
Xcode 8.2 不能编译通过

### ISSUE THREAD

**Issue by Hengyu** [shengbinmeng/UniBBS#26]
cd 到 project 路径下后执行 pod install 之后再 build ,结果如图

<img width="817" alt="2016-12-17 8 49 38" src="https://cloud.githubusercontent.com/assets/4032674/21286903/0e504bf4-c49b-11e6-8996-1b47cbbab924.png">

**Comment by shengbinmeng** [comment]
你这是新clone下来就这样吗？还是更新后导致的？如果是后者，可以尝试先`pod deintegrate`后再`pod install`。更新后可能导致pod与Xcode的集成坏掉了。

**Comment by Hengyu** [comment]
这是新 clone 下来的.然后我 `pod deintegrate` `pod clean` `pod install`再试了一次,还是报错.
<img width="392" alt="2016-12-17 9 52 35" src="https://cloud.githubusercontent.com/assets/4032674/21287295/46ac2f2e-c4a3-11e6-821f-fbed587acb4e.png">

**Comment by Hengyu** [comment]
错误和以前不一样了,貌似之前的错误被解决了.我看了下"Linked Frameworks and Libraries",显示在`pod deintegrate`后少了某个链接库(应该是生成的 pod 文件).所以可能导致了第二个错误.

**Comment by shengbinmeng** [comment]
你新clone下来直接按照README所说的步骤执行会报错吗？（我这儿还没升级到Xcode 8.2没法试，不过Xcode 8.1是没问题的）

**Comment by Hengyu** [comment]
恩,我是按照顺序做的.但并没有找到`UniBBS.xcworkspace`,只`UniBBS.xcodeproj`.

**Comment by shengbinmeng** [comment]
啊？那你上面的截图怎么得到的？如果没有找到UniBBS.xcworkspace，那说明已经出问题了，就不要往下进行了任何操作了，否则肯定是错的。

**Comment by Hengyu** [comment]
我打开的是"UniBBS.xcodeproj",而不是"UniBBS.xcworkspace".这个项目也只有前者啊.
<img width="1053" alt="2016-12-17 10 16 46" src="https://cloud.githubusercontent.com/assets/4032674/21287444/97ffc2ca-c4a6-11e6-98c7-17fc35f82170.png">
确实,按照常理应该是打开 xcworkspace 的,然后 xcworkspace 里包含了对本 project 和 pod 的引用.

**Comment by shengbinmeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1195838/21287459/e99cb05c-c4a6-11e6-8cce-60ffaf6c22e1.png)

明确说要“打开生成的UniBBS.xcworkspace文件”……（打开UniBBS.xcodeproj是不应该的，也不会正确编译）。

那么你现在的情况是执行`pod install`后没有生成这个文件？你能否把你的pod的版本（`pod --version`）和在**全新clone的**项目根目录下运行`pod install`的执行结果截图看看？我升级到Xcode 8.2还等一会儿，不过我觉得不该是Xcode版本的问题呀。

**Comment by Hengyu** [comment]
version是1.1.1, `pod install`后没有生成xcworkspace文件.

**Comment by shengbinmeng** [comment]
pod版本跟我的是一样的。`pod install`命令的输出是什么？能把结果贴出来看看吗？

**Comment by Hengyu** [comment]
<img width="355" alt="2016-12-17 10 43 18" src="https://cloud.githubusercontent.com/assets/4032674/21287604/4813b4a2-c4aa-11e6-9896-c9f3dfa9dfe7.png">

**Comment by shengbinmeng** [comment]
可以看到命令abort了，这是pod的问题。可参考：http://stackoverflow.com/questions/39980096/xcode8-cocoapods-abort-trap6/40438232#40438232。

我大概看了一下，要么进一步更新pod，要么用较新的ruby。我用的是自己装的ruby，2.3.1。我估计你用的是macOS系统自带的ruby，2.0.0。

**Comment by shengbinmeng** [comment]
另参见：https://github.com/CocoaPods/CocoaPods/issues/6169

**Comment by Hengyu** [comment]
多谢,因该是这样的.我也看到了这个帖子.正在更新 ruby 中.

**Comment by Hengyu** [comment]
终于好了,好曲折.珍爱生命,远离 cocoapods.

**Comment by shengbinmeng** [comment]
确实，能用系统API直接实现的最好就自己做，而非用第三方的库。
