### ISSUE TITLE
alertView多次出现

### ISSUE THREAD

**Issue by fanyingming** [shengbinmeng/UniBBS#4]
一种情况，网络访问不到bbs数据，首先是获取不到热点数据，然后立即点到登陆输入账户信息登陆，此时popularView里网络错误的alertView会弹出。
我们是否应该检测如果当前view不在屏幕显示，就不alert？以及怎么编码实现？
@shengbinmeng

**Comment by shengbinmeng** [comment]
采用官方API后已重新设计错误处理流程。
